# Generated by Django 3.0.2 on 2020-01-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('grade', models.IntegerField(default=11)),
                ('subject', models.CharField(default='Both', max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
